apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-certificate
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nanni237@gmail.com
    privateKeySecretRef:
      name: cert-manager.letsencrypt.key.tls
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager.cloudflare.api.token
            key: api-token
