apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      targetRevision: 4.0.18
      helm:
        valuesObject:
          nfs:
            server: 192.168.1.4
            path: /mnt/data/apps
          storageClass:
            defaultClass: true

    - repoURL: 'https://github.com/nanni237/themanor'
      targetRevision: main
      path: 'apps/nfs-provisioner'
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
