apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-k8s
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/nanni237/themanor'
      targetRevision: main
      path: 'infra/k8s'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true