apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.3.3
          ports:
            - containerPort: 8123
          securityContext:
            privileged: true
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config
            - name: zigbee
              mountPath: /dev/ttyUSB0
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: zigbee
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice